import type { ReadingFolder, ReadingMaterial } from "./types";

export const readingFolders: ReadingFolder[] = [
  { id: "docs", name: "개발 문서", parentId: null, sortOrder: 1 },
  { id: "docs-react", name: "React", parentId: "docs", sortOrder: 1 },
  { id: "docs-tauri", name: "Tauri", parentId: "docs", sortOrder: 2 },
  { id: "books", name: "원서", parentId: null, sortOrder: 2 },
  { id: "exam", name: "시험 대비", parentId: null, sortOrder: 3 },
];

export const readingMaterials: ReadingMaterial[] = [
  {
    id: 1,
    folderId: "docs-tauri",
    title: "Why docs use should",
    sourceType: "공식 문서",
    level: "B2",
    status: "학습 가능",
    sourceUrl: "https://example.com/docs/should",
    collectedDate: "2026-07-06",
    savedAt: "오늘 오전 12:08",
    wordCount: 420,
    estimatedMinutes: 8,
  },
  {
    id: 2,
    folderId: "docs-react",
    title: "How readers infer intent",
    sourceType: "기사",
    level: "B1",
    status: "분석 대기",
    sourceUrl: "https://example.com/articles/intent",
    collectedDate: "2026-07-06",
    savedAt: "어제 오후 11:42",
    wordCount: 680,
    estimatedMinutes: 12,
  },
  {
    id: 3,
    folderId: "docs",
    title: "API warnings and notes",
    sourceType: "공식 문서",
    level: "C1",
    status: "원문 저장",
    sourceUrl: "https://example.com/api/warnings",
    collectedDate: "2026-07-05",
    savedAt: "어제 오후 10:13",
    wordCount: 350,
    estimatedMinutes: 7,
  },
  {
    id: 4,
    folderId: "books",
    title: "Chapter opening paragraphs",
    sourceType: "원서",
    level: "B2",
    status: "분석 대기",
    sourceUrl: "local://book/chapter-1",
    collectedDate: "2026-07-04",
    savedAt: "7월 4일 오후 09:10",
    wordCount: 920,
    estimatedMinutes: 16,
  },
];
